# Generated by Django 5.2.1 on 2025-06-13 11:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('rtsp_url', models.CharField(help_text='RTSP URL of the camera (e.g., rtsp://user:pass@ip:port/stream)', max_length=500, unique=True)),
                ('stream_url', models.CharField(blank=True, help_text='Generated web-friendly stream URL (e.g., HLS .m3u8). This will be managed by your streaming server.', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cameras',
                'ordering': ['name'],
            },
        ),
    ]
