# Generated by Django 5.2.1 on 2025-06-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ffmpeg_process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
    ]
